<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6b90386c373c25314e64f7ba7b5b316d
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Fauxpress\\SiteHygiene\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Fauxpress\\SiteHygiene\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6b90386c373c25314e64f7ba7b5b316d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6b90386c373c25314e64f7ba7b5b316d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit6b90386c373c25314e64f7ba7b5b316d::$classMap;

        }, null, ClassLoader::class);
    }
}
